name: Build and Push NodeJS Image to AWS ECR
on: 
  push:
    branches: [ "master" ]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS cerdentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: 
        bash ./build/git_update.sh -v major

    - name: Build, Tag, Image to AWS ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: lesson-086
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run:
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .    

    - name: Push the Image to AWS ECR
      id: push-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: lesson-086
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run:
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
